sudo: required
services:
  - docker
before_install:
  - docker build -t vivekraj59/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true vivekraj59/react-test npm test

after_success:
  - docker build -t vivekraj59/multi-client ./client
  - docker build -t vivekraj59/multi-nginx ./nginx
  - docker build -t vivekraj59/multi-server ./server
  - docker build -t vivekraj59/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push vivekraj59/multi-client
  - docker push vivekraj59/multi-nginx
  - docker push vivekraj59/multi-server
  - docker push vivekraj59/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-806866393353
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  